### ISSUE TITLE
No longer compatible with latest aa-vex-base release

### ISSUE THREAD

**Issue by jilleb** [martoreto/aastats#2]
The current version is working with v3.1, but it's no longer compatible with v4.3

**Comment by martoreto** [comment]
Ah, sorry for this one. I made an update to aa-vex-base, which now supports providing the list of available signals to aastats, but did not complete the update on this side yet. The update was needed for the correct uploading of data for to BigQuery, which I use all the time.

Leaving this ticket open until I finish the update to aastats.

**Comment by martoreto** [comment]
Updated to the newest version, now with schema support, so that aastats now knows what values are provided by the car.
